Repository kadena-io/pact, pull requests merged in 2018-11, with the labels that each got.

#297 Update docs for new property syntax.
  docs/pact-properties.md
Labels: docs

#301 Add property documentation for column-of
  src/Pact/Analyze/Feature.hs
Labels: FV, docs

#302 Fix constraint vacuity for single-case enforce-one
  src/Pact/Analyze/Eval/Term.hs
  src/Pact/Analyze/Translate.hs
  tests/AnalyzeSpec.hs
Labels: FV, bug

#287 Japanese ReadTheDocs
  docs/README.md
  docs/build.sh
  docs/en/conf.py
  docs/en/img
  docs/en/index.rst
  docs/en/pact-functions.md
  docs/en/pact-functions.rst
  docs/en/pact-properties-api.md
  docs/en/pact-properties-api.rst
  docs/en/pact-properties.md
  docs/en/pact-properties.rst
  docs/en/pact-reference.md
  docs/en/pact-reference.rst
  docs/en/pacts.md
  docs/jp/conf.py
  docs/jp/img
  docs/jp/index.rst
  docs/jp/pact-reference.md
  docs/jp/pact-reference.rst
  src/Pact/Docgen.hs
Labels: docs

#305 Fix model extraction for arguments
  src/Pact/Analyze/Check.hs
  src/Pact/Analyze/Model/Tags.hs
  src/Pact/Analyze/Translate.hs
  tests/AnalyzeSpec.hs
Labels: FV, bug
